repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files


  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.6.7  # Версия Ruff на момент написания
    hooks:
      - id: ruff
        args: ["--fix"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.2.0  # Версия mypy на момент написания
    hooks:
      - id: mypy
        args: ["--ignore-missing-imports"]  # Измените это, если хотите строгую проверку импортов
